-- DROP and CREATE users TABLE
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
user_id SERIAL PRIMARY KEY NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
email VARCHAR UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT NOW()
);  